apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordcounter
  namespace: production
spec:
  rules:
  - host: wordcounter.org
    http:
      paths:
      - path: /
        backend:
          serviceName: wordcounter
          servicePort: 5000


