apiVersion: v1
kind: Service
metadata:
  labels:
    run: frontend
  name: frontend
  namespace: production
spec:
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    run: frontend
  sessionAffinity: ClientIP
