apiVersion: v1
kind: Service
metadata:
  labels:
    run: scrape-website-text
  name: scrape-website-text
  namespace: default
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    run: scrape-website-text
  sessionAffinity: None
