apiVersion: v1
kind: Service
metadata:
  labels:
    run: scraper
  name: scraper
  namespace: default
spec:
  ports:
  - port: 6000
    targetPort: 6000
  selector:
    run: scraper
  sessionAffinity: None
